#!/bin/bash

case "$1" in
    'configure')
        
        if [ ! -e /etc/ros ]
        then
            ln -s /etc/ros-groovy /etc/ros
        fi
        if [ -e "/var/lib/ros" ]; then
	    chown -R ros:ros /var/lib/ros
            chmod 2775 /var/lib/ros
	fi
        if getent passwd ros >/dev/null; then
            setuidgid ros env ROS_HOME=/var/lib/ros/.ros rosdep update
            if ! [ -e "/etc/skel/.ros" ]; then
                mkdir -p /etc/skel/.ros
            fi
            cp -r /var/lib/ros/.ros/rosdep /etc/skel/.ros/.
            cp /var/lib/ros/.ros/rospack_cache /etc/skel/.ros/.
        fi

        ;;

    *)
        ;;

esac
#DEBHELPER#
