#!/bin/bash

case "$1" in
    'configure')
        
        if [ ! -e /etc/ros ]
        then
            ln -s /etc/ros-groovy /etc/ros
        fi
        if getent passwd ros >/dev/null; then
            setuidgid ros source /etc/ros/setup.bash && rosdep update
        fi
        ;;

    *)
        ;;

esac
#DEBHELPER#
